services:
  - type: web
    name: immunifhir-frontend
    env: node
    rootDir: immunifhir-frontend/immunifhir-frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --port 10000
    plan: free
